### ISSUE TITLE
Incomple Readme.md  file

### ISSUE THREAD

**Issue by yuvarajvemula** [RamuRChenchaiah/virus-scanner-nodejs#1]
The requirements and installation procedures are in incomplete stage . This makes others ,
Hard/impossible to test and understand about this repository..

**Comment by RamuRChenchaiah** [comment]
Hi,
This is under progress. Would update shortly. Thanks

**Comment by yuvarajvemula** [comment]
:smiley:  :thumbsup: @RamuRChenchaiah 
Thanks for your kind reply.
I am new to nodejs and eager to mastering myself from your repository works.

**Comment by RamuRChenchaiah** [comment]
Dear Shivaraj,

Thank you for your interest. I have updated the doc with required details. Hope it helps.

**Comment by yuvarajvemula** [comment]
:+1:
